// Copyright 2025 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcp

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"google.golang.org/api/batch/v1"
	"google.golang.org/api/compute/v1"
)

// BatchGenerator generates Terraform resources for Google Cloud Batch.
type BatchGenerator struct {
	GCPService
}

// InitResources initializes the Batch resources.
/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *BatchGenerator) InitResources() error {
	if g.GetArgs()["region"].(compute.Region).Name == "" || g.GetArgs()["region"].(compute.Region).Name == "global" {
		return nil
	}

	project := g.GetArgs()["project"].(string)
	location := g.GetArgs()["region"].(compute.Region).Name
	ctx := context.Background()

	batchService, err := batch.NewService(ctx)
	if err != nil {
		return fmt.Errorf("failed to create batch service: %w", err)
	}

	parent := fmt.Sprintf("projects/%s/locations/%s", project, location)
	req := batchService.Projects.Locations.Jobs.List(parent)

	if err := req.Pages(ctx, func(page *batch.ListJobsResponse) error {
		for _, job := range page.Jobs {
			parts := strings.Split(job.Name, "/")
			jobName := parts[len(parts)-1]

			g.Resources = append(g.Resources, terraformutils.NewResource(
				job.Name,
				jobName,
				"google_batch_job",
				g.ProviderName,
				map[string]string{
					"project":  project,
					"location": location,
					"name":     jobName,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	}); err != nil {
		log.Println(err)
		return fmt.Errorf("failed to list batch jobs: %w", err)
	}

	return nil
}
