// Copyright 2025 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcp

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"google.golang.org/api/certificatemanager/v1"
	"google.golang.org/api/compute/v1"
)

// CertificateManagerGenerator generates Terraform resources for Google Certificate Manager.
type CertificateManagerGenerator struct {
	GCPService
}

// InitResources initializes the Certificate Manager resources.
/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *CertificateManagerGenerator) InitResources() error {
	// Certificate Manager resources are global
	if g.GetArgs()["region"].(compute.Region).Name != "" && g.GetArgs()["region"].(compute.Region).Name != "global" {
		return nil
	}

	project := g.GetArgs()["project"].(string)
	ctx := context.Background()

	certManagerService, err := certificatemanager.NewService(ctx)
	if err != nil {
		return fmt.Errorf("failed to create certificate manager service: %w", err)
	}

	parent := fmt.Sprintf("projects/%s/locations/global", project)

	if err := g.initCertificates(ctx, certManagerService, parent, project); err != nil {
		return err
	}
	if err := g.initCertificateMaps(ctx, certManagerService, parent, project); err != nil {
		return err
	}
	if err := g.initDnsAuthorizations(ctx, certManagerService, parent, project); err != nil {
		return err
	}
	if err := g.initTrustConfigs(ctx, certManagerService, parent, project); err != nil {
		return err
	}

	return nil
}

func (g *CertificateManagerGenerator) initTrustConfigs(ctx context.Context, service *certificatemanager.Service, parent, project string) error {
	req := service.Projects.Locations.TrustConfigs.List(parent)
	if err := req.Pages(ctx, func(page *certificatemanager.ListTrustConfigsResponse) error {
		for _, config := range page.TrustConfigs {
			parts := strings.Split(config.Name, "/")
			configName := parts[len(parts)-1]
			g.Resources = append(g.Resources, terraformutils.NewResource(
				config.Name,
				configName,
				"google_certificate_manager_trust_config",
				g.ProviderName,
				map[string]string{
					"project":  project,
					"location": "global",
					"name":     configName,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	}); err != nil {
		log.Println(err)
		return fmt.Errorf("failed to list trust configs: %w", err)
	}
	return nil
}

func (g *CertificateManagerGenerator) initCertificates(ctx context.Context, service *certificatemanager.Service, parent, project string) error {
	req := service.Projects.Locations.Certificates.List(parent)
	if err := req.Pages(ctx, func(page *certificatemanager.ListCertificatesResponse) error {
		for _, cert := range page.Certificates {
			parts := strings.Split(cert.Name, "/")
			certName := parts[len(parts)-1]
			g.Resources = append(g.Resources, terraformutils.NewResource(
				cert.Name,
				certName,
				"google_certificate_manager_certificate",
				g.ProviderName,
				map[string]string{
					"project":  project,
					"location": "global",
					"name":     certName,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	}); err != nil {
		log.Println(err)
		return fmt.Errorf("failed to list certificates: %w", err)
	}
	return nil
}

func (g *CertificateManagerGenerator) initCertificateMaps(ctx context.Context, service *certificatemanager.Service, parent, project string) error {
	req := service.Projects.Locations.CertificateMaps.List(parent)
	if err := req.Pages(ctx, func(page *certificatemanager.ListCertificateMapsResponse) error {
		for _, certMap := range page.CertificateMaps {
			parts := strings.Split(certMap.Name, "/")
			mapName := parts[len(parts)-1]
			g.Resources = append(g.Resources, terraformutils.NewResource(
				certMap.Name,
				mapName,
				"google_certificate_manager_certificate_map",
				g.ProviderName,
				map[string]string{
					"project":  project,
					"location": "global",
					"name":     mapName,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	}); err != nil {
		log.Println(err)
		return fmt.Errorf("failed to list certificate maps: %w", err)
	}
	return nil
}

func (g *CertificateManagerGenerator) initDnsAuthorizations(ctx context.Context, service *certificatemanager.Service, parent, project string) error {
	req := service.Projects.Locations.DnsAuthorizations.List(parent)
	if err := req.Pages(ctx, func(page *certificatemanager.ListDnsAuthorizationsResponse) error {
		for _, dnsAuth := range page.DnsAuthorizations {
			parts := strings.Split(dnsAuth.Name, "/")
			authName := parts[len(parts)-1]
			g.Resources = append(g.Resources, terraformutils.NewResource(
				dnsAuth.Name,
				authName,
				"google_certificate_manager_dns_authorization",
				g.ProviderName,
				map[string]string{
					"project":  project,
					"location": "global",
					"name":     authName,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	}); err != nil {
		log.Println(err)
		return fmt.Errorf("failed to list dns authorizations: %w", err)
	}
	return nil
}
