// Copyright 2025 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcp

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"google.golang.org/api/compute/v1"
	"google.golang.org/api/domains/v1"
)

// CloudDomainsGenerator generates Terraform resources for Google Cloud Domains.
type CloudDomainsGenerator struct {
	GCPService
}

// InitResources initializes the Cloud Domains resources.
/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *CloudDomainsGenerator) InitResources() error {
	// Cloud Domains are global resources
	if g.GetArgs()["region"].(compute.Region).Name != "" && g.GetArgs()["region"].(compute.Region).Name != "global" {
		return nil
	}

	project := g.GetArgs()["project"].(string)
	ctx := context.Background()

	domainsService, err := domains.NewService(ctx)
	if err != nil {
		return fmt.Errorf("failed to create domains service: %w", err)
	}

	// Cloud Domains registrations are global, so we use "global" as location
	parent := fmt.Sprintf("projects/%s/locations/global", project)
	req := domainsService.Projects.Locations.Registrations.List(parent)

	if err := req.Pages(ctx, func(page *domains.ListRegistrationsResponse) error {
		for _, registration := range page.Registrations {
			parts := strings.Split(registration.Name, "/")
			registrationName := parts[len(parts)-1]

			g.Resources = append(g.Resources, terraformutils.NewResource(
				registration.Name,
				registrationName,
				"google_clouddomains_registration",
				g.ProviderName,
				map[string]string{
					"project":  project,
					"location": "global",
					"name":     registrationName,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	}); err != nil {
		log.Println(err)
		return fmt.Errorf("failed to list cloud domains registrations: %w", err)
	}

	return nil
}
