// Copyright 2025 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcp

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"google.golang.org/api/compute/v1"
	"google.golang.org/api/datamigration/v1"
	"google.golang.org/api/option"
)

type DatabaseMigrationGenerator struct {
	GCPService
}

/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *DatabaseMigrationGenerator) InitResources() error {
	ctx := context.Background()
	project := g.GetArgs()["project"].(string)
	dmsService, err := datamigration.NewService(ctx, option.WithQuotaProject(project))
	if err != nil {
		return err
	}

	region := g.GetArgs()["region"].(compute.Region).Name

	if region == "global" || region == "" {
		return nil
	}

	parent := fmt.Sprintf("projects/%s/locations/%s", project, region)

	// Connection Profiles
	cpReq := dmsService.Projects.Locations.ConnectionProfiles.List(parent)
	if err := cpReq.Pages(ctx, func(page *datamigration.ListConnectionProfilesResponse) error {
		for _, cp := range page.ConnectionProfiles {
			parts := strings.Split(cp.Name, "/")
			cpID := parts[len(parts)-1]

			g.Resources = append(g.Resources, terraformutils.NewResource(
				cp.Name,
				cpID,
				"google_database_migration_service_connection_profile",
				g.ProviderName,
				map[string]string{
					"project":               project,
					"location":              region,
					"connection_profile_id": cpID,
					"name":                  cpID,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	}); err != nil {
		log.Println(err)
	}

	// Migration Jobs
	mjReq := dmsService.Projects.Locations.MigrationJobs.List(parent)
	if err := mjReq.Pages(ctx, func(page *datamigration.ListMigrationJobsResponse) error {
		for _, mj := range page.MigrationJobs {
			parts := strings.Split(mj.Name, "/")
			mjID := parts[len(parts)-1]

			g.Resources = append(g.Resources, terraformutils.NewResource(
				mj.Name,
				mjID,
				"google_database_migration_service_migration_job",
				g.ProviderName,
				map[string]string{
					"project":          project,
					"location":         region,
					"migration_job_id": mjID,
					"name":             mjID,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	}); err != nil {
		log.Println(err)
	}

	return nil
}
