// Copyright 2025 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcp

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"google.golang.org/api/compute/v1"
	"google.golang.org/api/eventarc/v1"
)

// EventarcGenerator generates Terraform resources for Google Cloud Eventarc.
type EventarcGenerator struct {
	GCPService
}

// InitResources initializes the Eventarc resources.
/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *EventarcGenerator) InitResources() error {
	if g.GetArgs()["region"].(compute.Region).Name == "" || g.GetArgs()["region"].(compute.Region).Name == "global" {
		return nil
	}

	project := g.GetArgs()["project"].(string)
	location := g.GetArgs()["region"].(compute.Region).Name
	ctx := context.Background()

	eventarcService, err := eventarc.NewService(ctx)
	if err != nil {
		return fmt.Errorf("failed to create eventarc service: %w", err)
	}

	parent := fmt.Sprintf("projects/%s/locations/%s", project, location)
	req := eventarcService.Projects.Locations.Triggers.List(parent)

	if err := req.Pages(ctx, func(page *eventarc.ListTriggersResponse) error {
		for _, trigger := range page.Triggers {
			parts := strings.Split(trigger.Name, "/")
			triggerName := parts[len(parts)-1]

			g.Resources = append(g.Resources, terraformutils.NewResource(
				trigger.Name,
				triggerName,
				"google_eventarc_trigger",
				g.ProviderName,
				map[string]string{
					"project":  project,
					"location": location,
					"name":     triggerName,
				},
				[]string{},
				map[string]interface{}{},
			))

			if err := g.initTriggerIamPolicy(ctx, eventarcService, trigger.Name, triggerName, project, location); err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		log.Println(err)
		return fmt.Errorf("failed to list eventarc triggers: %w", err)
	}

	return nil
}

func (g *EventarcGenerator) initTriggerIamPolicy(ctx context.Context, service *eventarc.Service, triggerFullName, triggerName, project, location string) error {
	policy, err := service.Projects.Locations.Triggers.GetIamPolicy(triggerFullName).Do()
	if err != nil {
		return fmt.Errorf("failed to get iam policy for eventarc trigger %s: %w", triggerName, err)
	}

	for _, binding := range policy.Bindings {
		attributes := map[string]string{
			"project":  project,
			"location": location,
			"name":     triggerName,
		}
		conditionTitle := ""
		conditionDescription := ""
		conditionExpression := ""
		if binding.Condition != nil {
			conditionTitle = binding.Condition.Title
			conditionDescription = binding.Condition.Description
			conditionExpression = binding.Condition.Expression
		}
		g.Resources = append(g.Resources, g.CreateIamMemberResources(triggerFullName, triggerName, "google_eventarc_trigger_iam_member", attributes, binding.Role, binding.Members, conditionTitle, conditionDescription, conditionExpression)...)
	}
	return nil
}
