// Copyright 2025 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcp

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"google.golang.org/api/compute/v1"
	"google.golang.org/api/file/v1"
)

type FilestoreGenerator struct {
	GCPService
}

/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *FilestoreGenerator) InitResources() error {
	ctx := context.Background()
	fileService, err := file.NewService(ctx)
	if err != nil {
		return err
	}

	project := g.GetArgs()["project"].(string)
	parent := fmt.Sprintf("projects/%s", project)
	isGlobal := g.GetArgs()["region"].(compute.Region).Name == "" || g.GetArgs()["region"].(compute.Region).Name == "global"
	currentRegion := g.GetArgs()["region"].(compute.Region).Name

	if isGlobal {
		return nil
	}

	// List locations
	locationsCall := fileService.Projects.Locations.List(parent)
	err = locationsCall.Pages(ctx, func(page *file.ListLocationsResponse) error {
		for _, location := range page.Locations {
			parts := strings.Split(location.Name, "/")
			locationId := parts[len(parts)-1]

			// Check if locationId matches currentRegion or is a zone in currentRegion
			if locationId != currentRegion && !strings.HasPrefix(locationId, currentRegion+"-") {
				continue
			}

			g.createInstances(ctx, fileService, location.Name)
		}
		return nil
	})
	if err != nil {
		return err
	}

	return nil
}

/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *FilestoreGenerator) createInstances(ctx context.Context, service *file.Service, parent string) {
	instancesCall := service.Projects.Locations.Instances.List(parent)
	err := instancesCall.Pages(ctx, func(page *file.ListInstancesResponse) error {
		for _, instance := range page.Instances {
			// instance.Name format: projects/{project}/locations/{location}/instances/{instance_id}
			parts := strings.Split(instance.Name, "/")
			instanceID := parts[len(parts)-1]
			location := parts[len(parts)-3]

			g.Resources = append(g.Resources, terraformutils.NewResource(
				instance.Name,
				instanceID,
				"google_filestore_instance",
				g.ProviderName,
				map[string]string{
					"project":  g.GetArgs()["project"].(string),
					"location": location,
					"name":     instanceID,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	})
	if err != nil {
		log.Println(err)
	}
}
