// Copyright 2025 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcp

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"google.golang.org/api/compute/v1"
	"google.golang.org/api/gkebackup/v1"
	"google.golang.org/api/option"
)

type GkeBackupGenerator struct {
	GCPService
}

/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *GkeBackupGenerator) InitResources() error {
	ctx := context.Background()
	project := g.GetArgs()["project"].(string)
	gkeBackupService, err := gkebackup.NewService(ctx, option.WithQuotaProject(project))
	if err != nil {
		return err
	}

	region := g.GetArgs()["region"].(compute.Region).Name

	if region == "global" || region == "" {
		return nil
	}

	parent := fmt.Sprintf("projects/%s/locations/%s", project, region)

	req := gkeBackupService.Projects.Locations.BackupPlans.List(parent)
	if err := req.Pages(ctx, func(page *gkebackup.ListBackupPlansResponse) error {
		for _, plan := range page.BackupPlans {
			parts := strings.Split(plan.Name, "/")
			planID := parts[len(parts)-1]

			g.Resources = append(g.Resources, terraformutils.NewResource(
				plan.Name,
				planID,
				"google_gke_backup_backup_plan",
				g.ProviderName,
				map[string]string{
					"project":  project,
					"location": region,
					"name":     planID,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	}); err != nil {
		log.Println(err)
		return err
	}

	return nil
}
