// Copyright 2025 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcp

import (
	"context"
	"fmt"
	"log"

	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"google.golang.org/api/compute/v1"
	"google.golang.org/api/option"
	"google.golang.org/api/orgpolicy/v2"
)

type OrgPolicyGenerator struct {
	GCPService
}

/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *OrgPolicyGenerator) InitResources() error {
	ctx := context.Background()
	project := g.GetArgs()["project"].(string)
	orgPolicyService, err := orgpolicy.NewService(ctx, option.WithQuotaProject(project))
	if err != nil {
		return err
	}

	parent := fmt.Sprintf("projects/%s", project)

	// Org Policies are global resources attached to a project
	if g.GetArgs()["region"].(compute.Region).Name != "" && g.GetArgs()["region"].(compute.Region).Name != "global" {
		return nil
	}

	req := orgPolicyService.Projects.Policies.List(parent)
	if err := req.Pages(ctx, func(page *orgpolicy.GoogleCloudOrgpolicyV2ListPoliciesResponse) error {
		for _, policy := range page.Policies {
			g.Resources = append(g.Resources, terraformutils.NewResource(
				policy.Name,
				policy.Name,
				"google_org_policy_policy",
				g.ProviderName,
				map[string]string{
					"parent": parent,
					"name":   policy.Name,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	}); err != nil {
		log.Println(err)
		return err
	}

	return nil
}
