// Copyright 2025 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcp

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"google.golang.org/api/compute/v1"
	"google.golang.org/api/recaptchaenterprise/v1"
)

// RecaptchaEnterpriseGenerator generates Terraform resources for Google Cloud Recaptcha Enterprise.
type RecaptchaEnterpriseGenerator struct {
	GCPService
}

// InitResources initializes the Recaptcha Enterprise resources.
/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *RecaptchaEnterpriseGenerator) InitResources() error {
	if g.GetArgs()["region"].(compute.Region).Name != "" && g.GetArgs()["region"].(compute.Region).Name != "global" {
		return nil
	}

	project := g.GetArgs()["project"].(string)
	ctx := context.Background()
	service, err := recaptchaenterprise.NewService(ctx)
	if err != nil {
		return fmt.Errorf("failed to create recaptcha enterprise service: %w", err)
	}

	parent := fmt.Sprintf("projects/%s", project)
	req := service.Projects.Keys.List(parent)
	if err := req.Pages(ctx, func(page *recaptchaenterprise.GoogleCloudRecaptchaenterpriseV1ListKeysResponse) error {
		for _, key := range page.Keys {
			parts := strings.Split(key.Name, "/")
			keyName := parts[len(parts)-1]
			g.Resources = append(g.Resources, terraformutils.NewResource(
				key.Name,
				keyName,
				"google_recaptcha_enterprise_key",
				g.ProviderName,
				map[string]string{
					"project":      project,
					"display_name": key.DisplayName,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	}); err != nil {
		log.Println(err)
		return fmt.Errorf("failed to list recaptcha enterprise keys: %w", err)
	}
	return nil
}
