// Copyright 2025 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcp

import (
	"context"
	"fmt"
	"log"

	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"google.golang.org/api/cloudresourcemanager/v1"
	"google.golang.org/api/compute/v1"
	"google.golang.org/api/option"
)

type ResourceManagerLienGenerator struct {
	GCPService
}

/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *ResourceManagerLienGenerator) InitResources() error {
	ctx := context.Background()
	project := g.GetArgs()["project"].(string)
	crmService, err := cloudresourcemanager.NewService(ctx, option.WithQuotaProject(project))
	if err != nil {
		return err
	}

	parent := fmt.Sprintf("projects/%s", project)

	// Liens are global resources attached to a project
	if g.GetArgs()["region"].(compute.Region).Name != "" && g.GetArgs()["region"].(compute.Region).Name != "global" {
		return nil
	}

	req := crmService.Liens.List().Parent(parent)
	if err := req.Pages(ctx, func(page *cloudresourcemanager.ListLiensResponse) error {
		for _, lien := range page.Liens {
			g.Resources = append(g.Resources, terraformutils.NewResource(
				lien.Name,
				lien.Name,
				"google_resource_manager_lien",
				g.ProviderName,
				map[string]string{
					"project": project,
					"parent":  parent,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	}); err != nil {
		log.Println(err)
		return err
	}

	return nil
}
