// Copyright 2025 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcp

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"google.golang.org/api/compute/v1"
	"google.golang.org/api/spanner/v1"
)

type SpannerGenerator struct {
	GCPService
}

/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *SpannerGenerator) InitResources() error {
	ctx := context.Background()
	spannerService, err := spanner.NewService(ctx)
	if err != nil {
		return err
	}

	project := g.GetArgs()["project"].(string)
	parent := fmt.Sprintf("projects/%s", project)
	isGlobal := g.GetArgs()["region"].(compute.Region).Name == "" || g.GetArgs()["region"].(compute.Region).Name == "global"
	currentRegion := g.GetArgs()["region"].(compute.Region).Name

	// List instances
	instancesCall := spannerService.Projects.Instances.List(parent)
	err = instancesCall.Pages(ctx, func(page *spanner.ListInstancesResponse) error {
		for _, instance := range page.Instances {
			configParts := strings.Split(instance.Config, "/")
			configId := configParts[len(configParts)-1]

			isRegional := strings.HasPrefix(configId, "regional-")

			if isGlobal {
				if isRegional {
					continue
				}
			} else {
				if !isRegional {
					continue
				}
				// Check if region matches
				region := strings.TrimPrefix(configId, "regional-")
				if region != currentRegion {
					continue
				}
			}

			g.createInstance(instance)
			g.createDatabases(ctx, spannerService, instance.Name)
			g.createInstancePartitions(ctx, spannerService, instance.Name)
		}
		return nil
	})
	if err != nil {
		return err
	}

	if isGlobal {
		g.createInstanceConfigs(ctx, spannerService, parent)
	}

	return nil
}

/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *SpannerGenerator) createInstance(instance *spanner.Instance) {
	// instance.Name format: projects/{project}/instances/{instance_id}
	parts := strings.Split(instance.Name, "/")
	instanceID := parts[len(parts)-1]

	g.Resources = append(g.Resources, terraformutils.NewResource(
		instance.Name,
		instanceID,
		"google_spanner_instance",
		g.ProviderName,
		map[string]string{
			"project": g.GetArgs()["project"].(string),
			"name":    instanceID,
		},
		[]string{},
		map[string]interface{}{},
	))
}

/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *SpannerGenerator) createDatabases(ctx context.Context, service *spanner.Service, instanceName string) {
	databasesCall := service.Projects.Instances.Databases.List(instanceName)
	err := databasesCall.Pages(ctx, func(page *spanner.ListDatabasesResponse) error {
		for _, database := range page.Databases {
			// database.Name format: projects/{project}/instances/{instance_id}/databases/{database_id}
			parts := strings.Split(database.Name, "/")
			databaseID := parts[len(parts)-1]
			instanceID := parts[len(parts)-3]

			g.Resources = append(g.Resources, terraformutils.NewResource(
				database.Name,
				databaseID,
				"google_spanner_database",
				g.ProviderName,
				map[string]string{
					"project":  g.GetArgs()["project"].(string),
					"instance": instanceID,
					"name":     databaseID,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	})
	if err != nil {
		log.Println(err)
	}
}

/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *SpannerGenerator) createInstanceConfigs(ctx context.Context, service *spanner.Service, parent string) {
	configsCall := service.Projects.InstanceConfigs.List(parent)
	err := configsCall.Pages(ctx, func(page *spanner.ListInstanceConfigsResponse) error {
		for _, config := range page.InstanceConfigs {
			// Only import custom configs (those with a BaseConfig)
			if config.BaseConfig == "" {
				continue
			}

			parts := strings.Split(config.Name, "/")
			configID := parts[len(parts)-1]

			g.Resources = append(g.Resources, terraformutils.NewResource(
				config.Name,
				configID,
				"google_spanner_instance_config",
				g.ProviderName,
				map[string]string{
					"project": g.GetArgs()["project"].(string),
					"name":    configID,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	})
	if err != nil {
		log.Println(err)
	}
}

/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *SpannerGenerator) createInstancePartitions(ctx context.Context, service *spanner.Service, instanceName string) {
	partitionsCall := service.Projects.Instances.InstancePartitions.List(instanceName)
	err := partitionsCall.Pages(ctx, func(page *spanner.ListInstancePartitionsResponse) error {
		for _, partition := range page.InstancePartitions {
			parts := strings.Split(partition.Name, "/")
			partitionID := parts[len(parts)-1]
			instanceID := parts[len(parts)-3]

			g.Resources = append(g.Resources, terraformutils.NewResource(
				partition.Name,
				partitionID,
				"google_spanner_instance_partition",
				g.ProviderName,
				map[string]string{
					"project":  g.GetArgs()["project"].(string),
					"instance": instanceID,
					"name":     partitionID,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	})
	if err != nil {
		log.Println(err)
	}
}
