// Copyright 2025 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcp

import (
	"context"
	"fmt"
	"log"

	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"google.golang.org/api/compute/v1"
)

type VpcPeeringGenerator struct {
	GCPService
}

/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *VpcPeeringGenerator) InitResources() error {
	ctx := context.Background()
	computeService, err := compute.NewService(ctx)
	if err != nil {
		return err
	}

	project := g.GetArgs()["project"].(string)
	isGlobal := g.GetArgs()["region"].(compute.Region).Name == "" || g.GetArgs()["region"].(compute.Region).Name == "global"
	if !isGlobal {
		return nil
	}

	return g.createVpcPeerings(ctx, computeService, project)
}

/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *VpcPeeringGenerator) createVpcPeerings(ctx context.Context, service *compute.Service, project string) error {
	req := service.Networks.List(project)
	if err := req.Pages(ctx, func(page *compute.NetworkList) error {
		for _, network := range page.Items {
			for _, peering := range network.Peerings {
				// Peering name is unique within the network.
				// Terraform import ID: project/network/peering_name
				id := fmt.Sprintf("%s/%s/%s", project, network.Name, peering.Name)
				g.Resources = append(g.Resources, terraformutils.NewResource(
					id,
					peering.Name,
					"google_compute_network_peering",
					g.ProviderName,
					map[string]string{
						"project": project,
						"network": network.Name,
						"name":    peering.Name,
					},
					[]string{},
					map[string]interface{}{},
				))
			}
		}
		return nil
	}); err != nil {
		log.Println(err)
		return err
	}
	return nil
}
