// Copyright 2025 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcp

import (
	"context"
	"log"

	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"google.golang.org/api/compute/v1"
)

type VpnGatewaysGenerator struct {
	GCPService
}

/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *VpnGatewaysGenerator) InitResources() error {
	ctx := context.Background()
	computeService, err := compute.NewService(ctx)
	if err != nil {
		return err
	}

	project := g.GetArgs()["project"].(string)
	isGlobal := g.GetArgs()["region"].(compute.Region).Name == "" || g.GetArgs()["region"].(compute.Region).Name == "global"
	if isGlobal {
		return nil
	}
	region := g.GetArgs()["region"].(compute.Region).Name

	return g.createVpnGateways(ctx, computeService, project, region)
}

/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *VpnGatewaysGenerator) createVpnGateways(ctx context.Context, service *compute.Service, project, region string) error {
	req := service.VpnGateways.List(project, region)
	if err := req.Pages(ctx, func(page *compute.VpnGatewayList) error {
		for _, gateway := range page.Items {
			g.Resources = append(g.Resources, terraformutils.NewResource(
				gateway.Name,
				gateway.Name,
				"google_compute_ha_vpn_gateway",
				g.ProviderName,
				map[string]string{
					"project": project,
					"region":  region,
					"name":    gateway.Name,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	}); err != nil {
		log.Println(err)
		return err
	}
	return nil
}
