// Copyright 2025 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcp

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"google.golang.org/api/compute/v1"
	"google.golang.org/api/iam/v1"
)

// WorkloadIdentityGenerator generates Terraform resources for Google Cloud Workload Identity.
type WorkloadIdentityGenerator struct {
	GCPService
}

// InitResources initializes the Workload Identity resources.
/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *WorkloadIdentityGenerator) InitResources() error {
	if g.GetArgs()["region"].(compute.Region).Name != "" && g.GetArgs()["region"].(compute.Region).Name != "global" {
		return nil
	}

	project := g.GetArgs()["project"].(string)
	ctx := context.Background()
	service, err := iam.NewService(ctx)
	if err != nil {
		return fmt.Errorf("failed to create iam service: %w", err)
	}

	parent := fmt.Sprintf("projects/%s/locations/global", project)
	req := service.Projects.Locations.WorkloadIdentityPools.List(parent)
	if err := req.Pages(ctx, func(page *iam.ListWorkloadIdentityPoolsResponse) error {
		for _, pool := range page.WorkloadIdentityPools {
			if pool.State == "DELETED" {
				continue
			}
			parts := strings.Split(pool.Name, "/")
			poolID := parts[len(parts)-1]
			g.Resources = append(g.Resources, terraformutils.NewResource(
				pool.Name,
				poolID,
				"google_iam_workload_identity_pool",
				g.ProviderName,
				map[string]string{
					"project":                   project,
					"workload_identity_pool_id": poolID,
				},
				[]string{},
				map[string]interface{}{},
			))

			if err := g.initWorkloadIdentityPoolIamPolicy(ctx, service, pool.Name, poolID, project); err != nil {
				return err
			}
			if err := g.initWorkloadIdentityPoolProviders(ctx, service, pool.Name, poolID, project); err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		log.Println(err)
		return fmt.Errorf("failed to list workload identity pools: %w", err)
	}

	return nil
}

func (g *WorkloadIdentityGenerator) initWorkloadIdentityPoolProviders(ctx context.Context, service *iam.Service, poolFullName, poolID, project string) error {
	req := service.Projects.Locations.WorkloadIdentityPools.Providers.List(poolFullName)
	if err := req.Pages(ctx, func(page *iam.ListWorkloadIdentityPoolProvidersResponse) error {
		for _, provider := range page.WorkloadIdentityPoolProviders {
			if provider.State == "DELETED" {
				continue
			}
			parts := strings.Split(provider.Name, "/")
			providerID := parts[len(parts)-1]
			g.Resources = append(g.Resources, terraformutils.NewResource(
				provider.Name,
				providerID,
				"google_iam_workload_identity_pool_provider",
				g.ProviderName,
				map[string]string{
					"project":                            project,
					"workload_identity_pool_id":          poolID,
					"workload_identity_pool_provider_id": providerID,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	}); err != nil {
		return fmt.Errorf("failed to list workload identity pool providers for pool %s: %w", poolID, err)
	}
	return nil
}

func (g *WorkloadIdentityGenerator) initWorkloadIdentityPoolIamPolicy(ctx context.Context, service *iam.Service, poolFullName, poolID, project string) error {
	policy, err := service.Projects.Locations.WorkloadIdentityPools.GetIamPolicy(poolFullName, &iam.GetIamPolicyRequest{}).Do()
	if err != nil {
		return fmt.Errorf("failed to get iam policy for workload identity pool %s: %w", poolID, err)
	}

	for _, binding := range policy.Bindings {
		attributes := map[string]string{
			"project":                   project,
			"workload_identity_pool_id": poolID,
		}
		conditionTitle := ""
		conditionDescription := ""
		conditionExpression := ""
		if binding.Condition != nil {
			conditionTitle = binding.Condition.Title
			conditionDescription = binding.Condition.Description
			conditionExpression = binding.Condition.Expression
		}
		g.Resources = append(g.Resources, g.CreateIamMemberResources(poolFullName, poolID, "google_iam_workload_identity_pool_iam_member", attributes, binding.Role, binding.Members, conditionTitle, conditionDescription, conditionExpression)...)
	}
	return nil
}
