// Copyright 2025 The Terraformer Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcp

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/GoogleCloudPlatform/terraformer/terraformutils"
	"google.golang.org/api/compute/v1"
	"google.golang.org/api/workflows/v1"
)

// WorkflowsGenerator generates Terraform resources for Google Cloud Workflows.
type WorkflowsGenerator struct {
	GCPService
}

// InitResources initializes the Workflows resources.
/**
 * @ai-generated Method generated by GitHub Copilot Agent.
 * @reviewed-by SJM
 */
func (g *WorkflowsGenerator) InitResources() error {
	if g.GetArgs()["region"].(compute.Region).Name == "" || g.GetArgs()["region"].(compute.Region).Name == "global" {
		return nil
	}

	project := g.GetArgs()["project"].(string)
	location := g.GetArgs()["region"].(compute.Region).Name
	ctx := context.Background()

	workflowsService, err := workflows.NewService(ctx)
	if err != nil {
		return fmt.Errorf("failed to create workflows service: %w", err)
	}

	parent := fmt.Sprintf("projects/%s/locations/%s", project, location)
	req := workflowsService.Projects.Locations.Workflows.List(parent)

	if err := req.Pages(ctx, func(page *workflows.ListWorkflowsResponse) error {
		for _, workflow := range page.Workflows {
			parts := strings.Split(workflow.Name, "/")
			workflowName := parts[len(parts)-1]

			g.Resources = append(g.Resources, terraformutils.NewResource(
				workflow.Name,
				workflowName,
				"google_workflows_workflow",
				g.ProviderName,
				map[string]string{
					"project": project,
					"region":  location,
					"name":    workflowName,
				},
				[]string{},
				map[string]interface{}{},
			))
		}
		return nil
	}); err != nil {
		log.Println(err)
		return fmt.Errorf("failed to list workflows: %w", err)
	}

	return nil
}

// PostConvertHook implements the PostConvertHook interface.
func (g *WorkflowsGenerator) PostConvertHook() error {
	for i, r := range g.Resources {
		if r.InstanceInfo.Type != "google_workflows_workflow" {
			continue
		}
		if val, ok := r.Item["source_contents"]; ok {
			if str, ok := val.(string); ok {
				// Escape ${ to $${ to prevent Terraform interpolation
				str = strings.ReplaceAll(str, "${", "$${")
				// Wrap in heredoc
				if !strings.HasPrefix(str, "<<") {
					g.Resources[i].Item["source_contents"] = fmt.Sprintf("<<EOF\n%s\nEOF", str)
				}
			}
		}
	}
	return nil
}
